TylersNewWebApp/Models/Category.cs
using System;
namespace TylersNewWebApp.Models
{
    public class Category
    {
        public int CategoryID { get; set; }
        public string Name { get; set; }
    }
}

TylersNewWebApp/Models/ErrorViewModel.cs
using System;

namespace TylersNewWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TylersNewWebApp/Models/RehabCenters.cs
using System;
using System.Collections.Generic;

namespace TylersNewWebApp.Models
{
    public class RehabCenters
    {
        public RehabCenters()
        {
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set;}
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public string Specialty { get; set; }
        public string SpecialtyID { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

TylersNewWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TylersNewWebApp.Models;

namespace TylersNewWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)] //??
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TylersNewWebApp/Controllers/RehabCentersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TylersNewWebApp.Models;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TylersNewWebApp.Controllers
{
    public class RehabCentersController : Controller
    {
        private readonly IRehabCentersRepository repo;

        public RehabCentersController(IRehabCentersRepository repo)
        {
            this.repo = repo;
        }

        public IActionResult ViewRehabCenters(int id)
        {
            var rehabCenters = repo.GetRehabCenters(id);

            return View(rehabCenters);
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var rehabCenters = repo.GetAllRehabCenters();

            return View(rehabCenters);
        }

        public IActionResult UpdateRehabCentersToDatabase(RehabCenters rehabCenters)
        {
            repo.UpdateRehabCenters(rehabCenters);

            return RedirectToAction("ViewRehabCenters", new { id = rehabCenters.ID });
        }

        public IActionResult UpdateProduct(int id)
        {
            RehabCenters rehab = repo.GetRehabCenters(id);

            repo.UpdateRehabCenters(rehab);

            if (rehab == null)
            {
                return View("ProductNotFound");
            }

            return View(rehab);
        }


        public IActionResult InsertRehabCenters()
        {
            var rehab = new RehabCenters();
            return View(rehab);
        }

        public IActionResult InsertRehabCentersToDatabase(RehabCenters rehabCentersToInsert)
        {
            repo.InsertRehabCenters(rehabCentersToInsert);

            return RedirectToAction("Index");
        }

        public IActionResult DeleteRehabCenters(RehabCenters rehabCenters)
        {
            repo.DeleteRehabCenters(rehabCenters);

            return RedirectToAction("Index");
        }

    }
}

TylersNewWebApp/Views/Home/Index.cshtml
<!DOCTYPE html>


<h3>Welcome</h3>

<br />
<br />
<br />

<html>
<head>
    <meta name="viewport" content="device-width, intitial-scale=1">
</head>
<body>
    <style>
    body { background-image: url('https://i.imgur.com/1jR97sN.jpg') }
    </style>
</body>
</html>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TylersNewWebApp/Views/RehabCenters/Index.cshtml

@model IEnumerable<RehabCenters>

<h2>RehabCenters</h2>

<div style="display: block">
    <a href="/RehabCenters/InsertRehabCenters/">Create a New RehabCenter</a>
</div>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>PhoneNumber</th>
        <th>Website</th>
        <th>Specialty</th>
        <th>SpecialtyID</th>
    </tr>

    @foreach (var rehabCenters in Model)
    {
        <tr>
            <td><a href=/RehabCenters/ViewRehabCenters/@rehabCenters.ID>@rehabCenters.ID</a></td>
            <td>@rehabCenters.Name</td>
            <td>@rehabCenters.Address</td>
            <td>@rehabCenters.PhoneNumber</td>
            <td>@rehabCenters.Website</td>
            <td>@rehabCenters.Specialty</td>
            <td>@rehabCenters.SpecialtyID</td>
        </tr>

    }
</table>


TylersNewWebApp/Views/RehabCenters/InsertRehabCenters.cshtml
@model RehabCenters
<h2>Create a New RehabCenter</h2>
@using (Html.BeginForm("InsertRehabCentersToDatabase", "RehabCenters", "Post"))
{
    <input asp-for="ID" type="hidden" value="" />

    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="" />

    <label asp-for="Address" class="control-label">Address</label>
    <input type="text" name="Address" class="form-control" value="" />

    <label asp-for="PhoneNumber" class="control-label">PhoneNumber</label>
    <input type="text" name="PhoneNumber" class="form-control" value="" />

    <label asp-for="Website" class="control-label">Website</label>
    <input type="text" name="Website" class="form-control" value="" />

    <label asp-for="Specialty" class="control-label">Specialty</label>
    <input type="text" name="Specialty" class="form-control" value="" />

    <label asp-for="SpecialtyID" class="control-label">SpecialtyID</label>
    <input type="text" name="SpecialtyID" class="form-control" value="" />

    //<label asp-for="Price" class="control-label">Price</label>
    //<input type="number" step="0.01" name="Price" class="form-control" />
    //<div class="form-group">
    //<label for="">Select a Category</label>
    //<select class="form-control" name="ID" value="">
    //@foreach (var cat in Model.Categories)
    //{
    //<option value="@cat.CategoryID">@cat.CategoryID @cat.Name</option>
    //}
    //</select>
    //</div>
    <input type="submit" value="Create RehabCenter" class="btn btn-primary" />
}

TylersNewWebApp/Views/RehabCenters/UpdateRehabCenters.cshtml
@model RehabCenters

<h2>Update @Model.Name</h2>


@using (Html.BeginForm("UpdateRehabCentersToDatabase", "RehabCenters", "Post"))
{
    <input asp-for="ID" type="hidden" value="@Model.ID" />

    <label asp-for="Name" class="" control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" />

    <label asp-for="Address" class="" control-label">Address</label>
    <input type="text" name="Address" class="form-control" value="@Model.Address" />

    <label asp-for="PhoneNumber" class="" control-label">PhoneNumber</label>
    <input type="text" name="PhoneNumber" class="form-control" value="@Model.PhoneNumber" />

    <label asp-for="Website" class="" control-label">Website</label>
    <input type="text" name="Website" class="form-control" value="@Model.Website" />

    <label asp-for="Specialty" class="" control-label">Specialty</label>
    <input type="text" name="Specialty" class="form-control" value="@Model.Specialty" />

    <label asp-for="SpecialtyID" class="" control-label">SpecialtyID</label>
    <input type="text" name="SpecialtyID" class="form-control" value="@Model.SpecialtyID" />

    <input type="submit" value="Update RehabCenter" class="btn btn-primary" />

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
}


TylersNewWebApp/Views/RehabCenters/ViewRehabCenters.cshtml
@model RehabCenters

<h3>@Model.Name Information</h3>

<style>
body { background-image: url('https://i.imgur.com/bsVSmEf.jpg'); }
</style>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>PhoneNumber</th>
        <th>Website</th>
        <th>Specialty</th>
        <th>SpecialtyID</th>
    </tr>
    <tr>
        <td>@Model.ID</td>
        <td>@Model.Name</td>
        <td>@Model.Address</td>
        <td>@Model.PhoneNumber</td>
        <td>@Model.Website</td>
        <td>@Model.Specialty</td>
        <td>@Model.SpecialtyID</td>
    </tr>

</table>


<div style="display: block">
    <a href="/RehabCenters/UpdateRehabCenters/@Model.ID">Update this RehabCenter</a>
</div>

<div style="display: block">
    @using (Html.BeginForm("DeleteRehabCenters", "RehabCenters", "Post"))
    {
        <input type="hidden" asp-for="ID" value="@Model.ID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this RehabCenter" />
    }
</div>

TylersNewWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TylersNewWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TylersNewWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RehabCenters" asp-action="Index">RehabCenters</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TylersNewWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>